const youthIntakeDefaultValues = {
      firstName: "",
      middleName: "",
      lastName: "",
      pronouns: "",
      dateOfBirth: "",
      phoneNumber: "",
      socialMedia: "",
      address: "",
      city: "",
      province: "",
      postalCode: "",
      email: "",
      emergencyContactFirstName: "",
      emergencyContactLastName: "",
      emergencyContactNumber: "",
      referredBy: "",
      firstNationMembership: "",
      treatyNumber: "",
      otherFirstNation: "",
      inCare: "",
      statusCFSFile: "",
      lastFaceToFace: "",
      cfsAgency: "",
      cfsAgentFullName: "",
      cfsAgentNumber: "",
      cfsAgentEmail: "",
      onReserve: "",
      apprehendedOnReserve: "",
      transitionFromReserve: "",
      currentlyStaying: "",
      currentlyStayingDuration: "",
      peopleHome: 0,
      homeMembers: [
        {
          firstName: "",
          middleName: "",
          lastName: "",
          relationship: "",
          phoneNumber: "",
          email: "",
        },
      ],
      educationalPersons: [
        {
          firstName: "",
          middleName: "",
          lastName: "",
          relationship: "",
          phoneNumber: "",
          email: "",
        },
      ],
      inSchool: "",
      schoolAttending: "",
      currentGrade: "",
      fullStudent: "",
      schoolSchedule: "",
      birthCertificate: false,
      driversLicense: false,
      healthCard: false,
      statusCard: false,
      enhancedID: false,
      studentID: false,
      bankAccount: "",
      incomeAssistance: "",
      caseWorkerFullName: "",
      caseWorkerPhoneNumber: "",
      caseWorkerEmail: "",
      youthJustice: "",
      custodySupportSpecified: "",
      accessElder: "",
      speakingOffice: "",
      youthWorkshops: "",
      disabilities: "",
      disabilitiesExplained: "",
      careExperience: "",
      kindSupport: "",
      personalGoals: "",
      additionalInformation: "",
      motherNation: "",
      accessElderExplained: "",
      connectedCommunity: "",
      connectedCommunityExplained: "",
      motherFirstName: "",
      motherMiddleName: "",
      motherLastName: "",
      fatherFirstName: "",
      fatherMiddleName: "",
      fatherLastName: "",
      fatherNation: "",
};

export default youthIntakeDefaultValues;