// Helper function to convert boolean to yes/no for radio buttons
const convertBooleanToYesNo = (value) => {
    if (value === true) return "yes";
    if (value === false) return "no";
    return ""; // Return empty string instead of null for unselected radio buttons
};

export const getFormInitialValues = ({
    originalData = {},
    childrenData = [],
    notesData = [],
    caseNotes = [],
    legalNotes = [],
    familyData = [],
    EIAData = [],
    homeMembersData = [],
    } = {}) => ({
    firstName: originalData?.firstName || "",
    middleName: originalData?.middleName || "",
    lastName: originalData?.lastName || "",
    dateOfBirth: originalData?.dateOfBirth ? originalData.dateOfBirth.split("T")[0] : "",
    phoneNumber: originalData?.phoneNumber || "",
    address: originalData?.address || "",
    city: originalData?.city || "",
    province: originalData?.province || "",
    postalCode: originalData?.postalCode || "",
    email: originalData?.email || "",
    relationshipToChildren: originalData?.relationshipToChildren || "",
    otherAdultsInvolved: originalData?.otherAdultsInvolved || "",
    otherAdultsInvolvedExplained: originalData?.otherAdultsInvolvedExplained || "",
    firstNationMembership: originalData?.firstNationMembership || "",
    treatyNumber: originalData?.treatyNumber || "",
    otherFirstNation: originalData?.otherFirstNation || "",
    ninePersonalHealthNumber: originalData?.ninePersonalHealthNumber || "",
    sixPersonalHealthNumber: originalData?.sixPersonalHealthNumber || "",
    onReserve: convertBooleanToYesNo(originalData?.onReserve),
    transitionFromReserve: convertBooleanToYesNo(originalData?.transitionFromReserve),
    previousFNFAOClient: convertBooleanToYesNo(originalData?.previousFNFAOClient),
    visitsChildFrequency: originalData?.visitsChildFrequency || "",
    casePlanCopy: convertBooleanToYesNo(originalData?.casePlanCopy),
    casePlanCopyDescribe: originalData?.casePlanCopyDescribe || "",
    prenatalSupport: convertBooleanToYesNo(originalData?.prenatalSupport),
    prenatalSupportSpecified: originalData?.prenatalSupportSpecified || "",
    housingSupport: convertBooleanToYesNo(originalData?.housingSupport),
    housingSupportSpecified: originalData?.housingSupportSpecified || "",
    addictionsSupport: convertBooleanToYesNo(originalData?.addictionsSupport),
    addictionsSupportSpecified: originalData?.addictionsSupportSpecified || "",
    youthSupport: convertBooleanToYesNo(originalData?.youthSupport),
    youthSupportSpecified: originalData?.youthSupportSpecified || "",
    custodySupport: convertBooleanToYesNo(originalData?.custodySupport),
    custodySupportSpecified: originalData?.custodySupportSpecified || "",
    criminalCharges: convertBooleanToYesNo(originalData?.criminalCharges),
    criminalChargesSpecified: originalData?.criminalChargesSpecified || "",
    activeWarrant: convertBooleanToYesNo(originalData?.activeWarrant),
    activeWarrantSpecified: originalData?.activeWarrantSpecified || "",
    activeInvestigation: convertBooleanToYesNo(originalData?.activeInvestigation),
    activeInvestigationExplained: originalData?.activeInvestigationExplained || "",
    activeOrders: convertBooleanToYesNo(originalData?.activeOrders),
    activeOrdersExplained: originalData?.activeOrdersExplained || "",
    currentLawyer: convertBooleanToYesNo(originalData?.currentLawyer),
    legalAssistance: convertBooleanToYesNo(originalData?.legalAssistance),
    legalAssistanceSpecified: originalData?.legalAssistanceSpecified || "",
    martialStatus: originalData?.martialStatus || "",
    dateModified: originalData?.dateModified ? originalData.dateModified.split("T")[0] : "",
    modifiedBy: originalData?.modifiedBy || "",
    createdAt: originalData?.createdAt ? originalData.createdAt.split("T")[0] : "",
    residentialSchool: convertBooleanToYesNo(originalData?.residentialSchool),
    cfsCare: convertBooleanToYesNo(originalData?.cfsCare),
    adoptedScoop: convertBooleanToYesNo(originalData?.adoptedScoop),
    experiencedSuicide: convertBooleanToYesNo(originalData?.experiencedSuicide),
    MMIWG2S: convertBooleanToYesNo(originalData?.MMIWG2S),
    familyViolence: convertBooleanToYesNo(originalData?.familyViolence),
    FASD: convertBooleanToYesNo(originalData?.FASD),
    ADHD: convertBooleanToYesNo(originalData?.ADHD),
    PTSD: convertBooleanToYesNo(originalData?.PTSD),
    depression: convertBooleanToYesNo(originalData?.depression),
    cancerAutoimmuneCondition: convertBooleanToYesNo(originalData?.cancerAutoimmuneCondition),
    otherMentalCondition: convertBooleanToYesNo(originalData?.otherMentalCondition),
    otherMentalConditionExplained: originalData?.otherMentalConditionExplained || "",
    diagnosedFollowingExplain: originalData?.diagnosedFollowingExplain || "",
    negativeCopingSkills: convertBooleanToYesNo(originalData?.negativeCopingSkills),
    negativeCopingSkillsExplain: originalData?.negativeCopingSkillsExplain || "",
    drugsImpact: originalData?.drugsImpact || "",
    lastTimeUsed: originalData?.lastTimeUsed || "",
    educationalGoals: convertBooleanToYesNo(originalData?.educationalGoals),
    educationalGoalsExplained: originalData?.educationalGoalsExplained || "",
    accessElder: convertBooleanToYesNo(originalData?.accessElder),
    accessElderExplained: originalData?.accessElderExplained || "",
    childrenInCareDuration: originalData?.childrenInCareDuration || "",
    cfsChildrenApprehesionReason: originalData?.cfsChildrenApprehesionReason || "",
    kinship: convertBooleanToYesNo(originalData?.kinship),
    kinshipExplained: originalData?.kinshipExplained || "",
    anyConcerns: originalData?.anyConcerns || "",
    prentativeSupport: convertBooleanToYesNo(originalData?.prentativeSupport),
    prentativeSupportExplained: originalData?.prentativeSupportExplained || "",
    privateAgreement: convertBooleanToYesNo(originalData?.privateAgreement),
    privateAgreementExplained: originalData?.privateAgreementExplained || "",
    previousInvolvement: convertBooleanToYesNo(originalData?.previousInvolvement),
    previousInvolvementExplain: originalData?.previousInvolvementExplain || "",
    parentalCapacityDone: convertBooleanToYesNo(originalData?.parentalCapacityDone),
    parentalCapacity: originalData?.parentalCapacity || "",
    cfsExplain: convertBooleanToYesNo(originalData?.cfsExplain),
    turnToKinshipCare: convertBooleanToYesNo(originalData?.turnToKinshipCare),
    sourceIncome: originalData?.sourceIncome !== null && originalData?.sourceIncome !== undefined ? originalData.sourceIncome : "",
    lawyerFullName: originalData?.lawyerFullName || "",
    lawyerPhoneNumber: originalData?.lawyerPhoneNumber || "",
    lawyerEmail: originalData?.lawyerEmail || "",
    children: childrenData.map(child => ({
        firstName: child.firstName || "",
        middleName: child.middleName || "",
        lastName: child.lastName || "",
        birthDate: child.birthDate || "",
        childNation: child.childNation || "",
        gender: child.gender || "",
        childPlaced: child.childPlaced || "",
        childCfsAgency: child.childCfsAgency || "",
        childCfsAgentFullName: child.childCfsAgentFullName || "",
        childCfsAgentNumber: child.childCfsAgentNumber !== null && child.childCfsAgentNumber !== undefined ? child.childCfsAgentNumber : "",
        childCfsAgentEmail: child.childCfsAgentEmail || "",
        childStatusCfsFile: child.childStatusCfsFile || "",
        childCfsSupervisorFullName: child.childCfsSupervisorFullName || "",
        childCfsSupervisorNumber: child.childCfsSupervisorNumber !== null && child.childCfsSupervisorNumber !== undefined ? child.childCfsSupervisorNumber : "",
        childCfsSupervisorEmail: child.childCfsSupervisorEmail || "",
        childMedicalNeeds: convertBooleanToYesNo(child?.childMedicalNeeds),
        childMedicalNeedsExplained: child?.childMedicalNeedsExplained || "",
        biologicalParentFirstName: child.biologicalParentFirstName || "",
        biologicalParentLastName: child.biologicalParentLastName || "",
        biologicalParentFirstNation: child.biologicalParentFirstNation || "",
    })) || [],
    notes: notesData || [],
    caseNotes: caseNotes || [],
    legalNotes: legalNotes || [],
    family: familyData || [],
    EIA: EIAData.map(worker => ({
        firstName: worker.firstName || "",
        lastName: worker.lastName || "",
        phoneNumber: worker.phoneNumber || "",
        EIACaseNumber: worker.EIACaseNumber || "",
    })) || [],
    homeMembers: homeMembersData.map(member => ({
        firstName: member.firstName || "",
        lastName: member.lastName || "",
        relationship: member.relationship || "",
        phoneNumber: member.phoneNumber || "",
        email: member.email || "",
        livingTogether: member.livingTogether
    })) || [],
    });




// export const getFormInitialValues = (originalData = {}) => ({
//         firstName: originalData?.firstName || "",
//         middleName: originalData?.middleName || "",
//         lastName: originalData?.lastName || "",
//         dateOfBirth: originalData?.dateOfBirth ? originalData.dateOfBirth.split("T")[0] : "",
//         phoneNumber: originalData?.phoneNumber || "",
//         address: originalData?.address || "",
//         city: originalData?.city || "",
//         province: originalData?.province || "",
//         postalCode: originalData?.postalCode || "",
//         email: originalData?.email || "",
//         relationshipToChildren: originalData?.relationshipToChildren || "",
//         otherAdultsInvolved: originalData?.otherAdultsInvolved !== undefined ? originalData.otherAdultsInvolved : null,
//         otherAdultsInvolvedExplained: originalData?.otherAdultsInvolvedExplained || "",
//         firstNationMembership: originalData?.firstNationMembership || "",
//         treatyNumber: originalData?.treatyNumber || "",
//         otherFirstNation: originalData?.otherFirstNation || "",
//         ninePersonalHealthNumber: originalData?.ninePersonalHealthNumber || "",
//         sixPersonalHealthNumber: originalData?.sixPersonalHealthNumber || "",
//         onReserve: originalData?.onReserve !== undefined ? originalData.onReserve : null,
//         transitionFromReserve: originalData?.transitionFromReserve !== undefined ? originalData.transitionFromReserve : null,
//         previousFNFAOClient: originalData?.previousFNFAOClient !== undefined ? originalData.previousFNFAOClient : null,
//         visitsChildFrequency: originalData?.visitsChildFrequency || "",
//         casePlanCopy: originalData?.casePlanCopy !== undefined ? originalData.casePlanCopy : null,
//         casePlanCopyDescribe: originalData?.casePlanCopyDescribe || "",
//         prenatalSupport: originalData?.prenatalSupport !== undefined ? originalData.prenatalSupport : null,
//         prenatalSupportSpecified: originalData?.prenatalSupportSpecified || "",
//         housingSupport: originalData?.housingSupport !== undefined ? originalData.housingSupport : null,
//         housingSupportSpecified: originalData?.housingSupportSpecified || "",
//         addictionsSupport: originalData?.addictionsSupport !== undefined ? originalData.addictionsSupport : null,
//         addictionsSupportSpecified: originalData?.addictionsSupportSpecified || "",
//         youthSupport: originalData?.youthSupport !== undefined ? originalData.youthSupport : null,
//         youthSupportSpecified: originalData?.youthSupportSpecified || "",
//         custodySupport: originalData?.custodySupport !== undefined ? originalData.custodySupport : null,
//         custodySupportSpecified: originalData?.custodySupportSpecified || "",
//         criminalCharges: originalData?.criminalCharges !== undefined ? originalData.criminalCharges : null,
//         criminalChargesSpecified: originalData?.criminalChargesSpecified || "",
//         activeWarrant: originalData?.activeWarrant !== undefined ? originalData.activeWarrant : null,
//         activeWarrantSpecified: originalData?.activeWarrantSpecified || "",
//         activeInvestigation: originalData?.activeInvestigation !== undefined ? originalData.activeInvestigation : null,
//         activeInvestigationExplained: originalData?.activeInvestigationExplained || "",
//         activeOrders: originalData?.activeOrders !== undefined ? originalData.activeOrders : null,
//         activeOrdersExplained: originalData?.activeOrdersExplained || "",
//         currentLawyer: originalData?.currentLawyer !== undefined ? originalData.currentLawyer : null,
//         legalAssistance: originalData?.legalAssistance !== undefined ? originalData.legalAssistance : null,
//         legalAssistanceSpecified: originalData?.legalAssistanceSpecified || "",
//         martialStatus: originalData?.martialStatus || "",
//         dateModified: originalData?.dateModified ? originalData.dateModified.split("T")[0] : "",
//         modifiedBy: originalData?.modifiedBy || "",
//         createdAt: originalData?.createdAt ? originalData.createdAt.split("T")[0] : "",
//         // residentialSchool: Boolean(originalData?.residentialSchool),
//         residentialSchool: originalData?.residentialSchool ?? null,
//         cfsCare: Boolean(originalData?.cfsCare),
//         adoptedScoop: Boolean(originalData?.adoptedScoop),
//         experiencedSuicide: Boolean(originalData?.experiencedSuicide),
//         MMIWG2S: Boolean(originalData?.MMIWG2S),
//         familyViolence: Boolean(originalData?.familyViolence),
//         FASD: Boolean(originalData?.FASD),
//         ADHD: Boolean(originalData?.ADHD),
//         PTSD: Boolean(originalData?.PTSD),
//         depression: Boolean(originalData?.depression),
//         cancerAutoimmuneCondition: Boolean(originalData?.cancerAutoimmuneCondition),
//         otherMentalCondition: Boolean(originalData?.otherMentalCondition),
//         otherMentalConditionExplained: originalData?.otherMentalConditionExplained || "",
//         diagnosedFollowingExplain: originalData?.diagnosedFollowingExplain || "",
//         negativeCopingSkills: originalData?.negativeCopingSkills !== undefined ? originalData.negativeCopingSkills : null,
//         negativeCopingSkillsExplain: originalData?.negativeCopingSkillsExplain || "",
//         drugsImpact: originalData?.drugsImpact || "",
//         lastTimeUsed: originalData?.lastTimeUsed || "",
//         educationalGoals: originalData?.educationalGoals !== undefined ? originalData.educationalGoals : null,
//         educationalGoalsExplained: originalData?.educationalGoalsExplained || "",
//         accessElder: originalData?.accessElder !== undefined ? originalData.accessElder : null,
//         accessElderExplained: originalData?.accessElderExplained || "",
//         childrenInCareDuration: originalData?.childrenInCareDuration || "",
//         cfsChildrenApprehesionReason: originalData?.cfsChildrenApprehesionReason || "",
//         kinship: originalData?.kinship !== undefined ? originalData.kinship : null,
//         kinshipExplained: originalData?.kinshipExplained || "",
//         anyConcerns: originalData?.anyConcerns || "",
//         prentativeSupport: originalData?.prentativeSupport !== undefined ? originalData.prentativeSupport : null,
//         prentativeSupportExplained: originalData?.prentativeSupportExplained || "",
//         privateAgreement: originalData?.privateAgreement !== undefined ? originalData.privateAgreement : null,
//         privateAgreementExplained: originalData?.privateAgreementExplained || "",
//         previousInvolvement: originalData?.previousInvolvement !== undefined ? originalData.previousInvolvement : null,
//         previousInvolvementExplain: originalData?.previousInvolvementExplain || "",
//         parentalCapacityDone: originalData?.parentalCapacityDone !== undefined ? originalData.parentalCapacityDone : null,
//         parentalCapacity: originalData?.parentalCapacity || "",
//         cfsExplain: originalData?.cfsExplain !== undefined ? originalData.cfsExplain : null,
//         turnToKinshipCare: originalData?.turnToKinshipCare !== undefined ? originalData.turnToKinshipCare : null,
//         sourceIncome: originalData?.sourceIncome !== null && originalData?.sourceIncome !== undefined ? originalData.sourceIncome : "",
//         lawyerFullName: originalData?.lawyerFullName || "",
//         lawyerPhoneNumber: originalData?.lawyerPhoneNumber || "",
//         lawyerEmail: originalData?.lawyerEmail || "",
//         children: childrenData.map(child => ({
//             firstName: child.firstName || "",
//             middleName: child.middleName || "",
//             lastName: child.lastName || "",
//             birthDate: child.birthDate || "",
//             childNation: child.childNation || "",
//             gender: child.gender || "",
//             childPlaced: child.childPlaced || "",
//             childCfsAgency: child.childCfsAgency || "",
//             childCfsAgentFullName: child.childCfsAgentFullName || "",
//             childCfsAgentNumber: child.childCfsAgentNumber !== null && child.childCfsAgentNumber !== undefined ? child.childCfsAgentNumber : "",
//             childCfsAgentEmail: child.childCfsAgentEmail || "",
//             childStatusCfsFile: child.childStatusCfsFile || "",
//             childCfsSupervisorFullName: child.childCfsSupervisorFullName || "",
//             childCfsSupervisorNumber: child.childCfsSupervisorNumber !== null && child.childCfsSupervisorNumber !== undefined ? child.childCfsSupervisorNumber : "",
//             childCfsSupervisorEmail: child.childCfsSupervisorEmail || "",
//             childMedicalNeeds: child?.childMedicalNeeds !== undefined ? child.childMedicalNeeds : null,
//             childMedicalNeedsExplained: child?.childMedicalNeedsExplained || "",
//             biologicalParentFirstName: child.biologicalParentFirstName || "",
//             biologicalParentLastName: child.biologicalParentLastName || "",
//             biologicalParentFirstNation: child.biologicalParentFirstNation || "",
//         })) || [],
//         notes: notesData || [],
//         caseNotes: caseNotes || [],
//         legalNotes: legalNotes || [],
//         family: familyData || [],
//         EIA: EIAData.map(worker => ({
//             firstName: worker.firstName || "",
//             lastName: worker.lastName || "",
//             phoneNumber: worker.phoneNumber || "",
//             EIACaseNumber: worker.EIACaseNumber || "",
//         })) || [],
//         homeMembers: homeMembersData || [],
//     //     firstName:originalData?.firstName || "",
//     //     middleName:originalData?.middleName || "",
//     //     lastName:originalData?.lastName || "",
//     //     dateOfBirth: originalData?.dateOfBirth ? originalData.dateOfBirth.split("T")[0] : "",
//     //     phoneNumber:originalData?.phoneNumber || "",
//     //     address: originalData?.address || "",
//     //     city: originalData?.city || "",
//     //     province: originalData?.province || "",
//     //     postalCode: originalData?.postalCode || "",
//     //     email: originalData?.email || "",
//     //     // emergencyContactFirstName: originalData?.emergencyContactFirstName || "",
//     //     // emergencyContactLastName: originalData?.emergencyContactLastName || "",
//     //     // emergencyContactNumber: originalData?.emergencyContactNumber || "",
//     //     // referredBy: "",
//     //     relationshipToChildren: originalData?.relationshipToChildren || "",
//     //     // otherAdultsInvolved: originalData?.otherAdultsInvolved === true ? "yes" : originalData?.otherAdultsInvolved === false ? "no" : "",
//     //     otherAdultsInvolved: originalData?.otherAdultsInvolved ? "yes" : (originalData?.otherAdultsInvolved === false ? "no" : ""),
//     //     otherAdultsInvolvedExplained: originalData?.otherAdultsInvolvedExplained || "",
//     //     firstNationMembership: originalData?.firstNationMembership || "",
//     //     treatyNumber: originalData?.treatyNumber || "",
//     //     otherFirstNation: originalData?.otherFirstNation || "",
//     //     ninePersonalHealthNumber: originalData?.ninePersonalHealthNumber || "",
//     //     sixPersonalHealthNumber: originalData?.sixPersonalHealthNumber || "",
//     //     // onReserve: clientData?.onReserve || "",
//     //     onReserve: originalData?.onReserve === true ? "yes" : originalData?.onReserve === false ? "no" : "",
//     //     // transitionFromReserve: clientData?.transitionFromReserve || "",
//     //     transitionFromReserve: originalData?.transitionFromReserve === true ? "yes" : originalData?.transitionFromReserve === false ? "no" : "",

//     //     previousFNFAOClient: originalData?.previousFNFAOClient === true ? "yes" : originalData?.previousFNFAOClient === false ? "no" : "",
//     //     // seekingAdvocacy: "",
//     //     // cfsAgency: "",
//     //     // cfsAgentFullName: "",
//     //     // cfsAgentNumber: "",
//     //     // cfsAgentEmail: "",
//     //     // statusCFSFile: "",
//     //     // visitsChild:'no',
//     //     visitsChildFrequency: originalData?.visitsChildFrequency || "",
//     //     casePlanCopy: originalData?.casePlanCopy === true ? "yes" : originalData?.casePlanCopy === false ? "no" : "",
//     //     casePlanCopyDescribe: originalData?.casePlanCopyDescribe || "",
//     //     // involvedCFSReason: "",
//     //     // prenatalSupport:clientData?.prenatalSupport || "",
//     //     prenatalSupport: originalData?.prenatalSupport === true ? "yes" : originalData?.prenatalSupport === false ? "no" : "",
//     //     prenatalSupportSpecified: originalData?.prenatalSupportSpecified || "",
//     //     // housingSupport:clientData?.housingSupport || "",
//     //     housingSupport: originalData?.housingSupport === true ? "yes" : originalData?.housingSupport === false ? "no" : "",
//     //     housingSupportSpecified: originalData?.housingSupportSpecified || "",
//     //     // addictionsSupport:clientData?.addictionsSupport || "",
//     //     addictionsSupport: originalData?.addictionsSupport === true ? "yes" : originalData?.addictionsSupport === false ? "no" : "",
//     //     addictionsSupportSpecified: originalData?.addictionsSupportSpecified || "",
//     //     youthSupport: originalData?.youthSupport ? "yes" : (originalData?.youthSupport === false ? "no" : null),
//     //     youthSupportSpecified: originalData?.youthSupportSpecified || "",
//     //     custodySupport: originalData?.custodySupport ? "yes" : (originalData?.custodySupport === false ? "no" : null),
//     //     custodySupportSpecified: originalData?.custodySupportSpecified || "",
//     //     criminalCharges: originalData?.criminalCharges ? "yes" : (originalData?.criminalCharges === false ? "no" : null),
//     //     criminalChargesSpecified: originalData?.criminalChargesSpecified || "",
//     //     activeWarrant: originalData?.activeWarrant ? "yes" : (originalData?.activeWarrant === false ? "no" : null),
//     //     activeWarrantSpecified: originalData?.activeWarrantSpecified || "",
//     //     activeInvestigation: originalData?.activeInvestigation ? "yes" : (originalData?.activeInvestigation === false ? "no" : null),
//     //     activeInvestigationExplained: originalData?.activeInvestigationExplained || "",
//     //     activeOrders: originalData?.activeOrders ? "yes" : (originalData?.activeOrders === false ? "no" : null),
//     //     activeOrdersExplained: originalData?.activeOrdersExplained || "",
//     //     currentLawyer: originalData?.currentLawyer ? "yes" : (originalData?.currentLawyer === false ? "no" : null),
//     //     legalAssistance: originalData?.legalAssistance ? "yes" : (originalData?.legalAssistance === false ? "no" : null),
//     //     legalAssistanceSpecified: originalData?.legalAssistanceSpecified || "",
//     //     // unableToAssistExplained: "",
//     //     // referForSupport : "",
//     //     martialStatus: originalData?.martialStatus || "",
//     //     dateModified : originalData?.dateModified ? originalData.dateModified.split("T")[0] : "",
//     //     modifiedBy: originalData?.modifiedBy || "",
//     //     createdAt: originalData?.createdAt ? originalData.createdAt.split("T")[0] : "",

//     //     residentialSchool: Boolean(originalData?.residentialSchool),
//     //     cfsCare: Boolean(originalData?.cfsCare),
//     //     adoptedScoop: Boolean(originalData?.adoptedScoop),
//     //     experiencedSuicide: Boolean(originalData?.experiencedSuicide),
//     //     MMIWG2S: Boolean(originalData?.MMIWG2S),
//     //     familyViolence: Boolean(originalData?.familyViolence),

//     //     FASD: Boolean(originalData?.FASD),
//     //     ADHD: Boolean(originalData?.ADHD),
//     //     PTSD: Boolean(originalData?.PTSD),
//     //     depression: Boolean(originalData?.depression),
//     //     cancerAutoimmuneCondition: Boolean(originalData?.cancerAutoimmuneCondition),
//     //     otherMentalCondition: Boolean(originalData?.otherMentalCondition),
//     //     otherMentalConditionExplained: originalData?.otherMentalConditionExplained || "",
//     //     diagnosedFollowingExplain:originalData?.diagnosedFollowingExplain || "",
//     //     negativeCopingSkills: originalData?.negativeCopingSkills ? "yes" : (originalData?.negativeCopingSkills === false ? "no" : ""),
//     //     negativeCopingSkillsExplain: originalData?.negativeCopingSkillsExplain || "",

//     //     drugsImpact: originalData?.drugsImpact || "",
//     //     lastTimeUsed: originalData?.lastTimeUsed || "",
//     //     educationalGoals: originalData?.educationalGoals ? "yes" : (originalData?.educationalGoals === false ? "no" : ""),
//     //     educationalGoalsExplained: originalData?.educationalGoalsExplained || "",
//     //     accessElder: originalData?.accessElder ? "yes" : (originalData?.accessElder === false ? "no" : ""),
//     //     accessElderExplained: originalData?.accessElderExplained || "",

//     //     childrenInCareDuration: originalData?.childrenInCareDuration || "",
//     //     cfsChildrenApprehesionReason: originalData?.cfsChildrenApprehesionReason || "",
//     //     kinship: originalData?.kinship ? "yes" : (originalData?.kinship === false ? "no" : ""),
//     //     kinshipExplained: originalData?.kinshipExplained || "",
//     //     anyConcerns: originalData?.anyConcerns || "",
//     //     prentativeSupport: originalData?.prentativeSupport ? "yes" : (originalData?.prentativeSupport === false ? "no" : ""),
//     //     prentativeSupportExplained: originalData?.prentativeSupportExplained || "",
//     //     privateAgreement: originalData?.privateAgreement ? "yes" : (originalData?.privateAgreement === false ? "no" : null), //asi para boleanos que esten nulos en la bd
//     //     privateAgreementExplained: originalData?.privateAgreementExplained || "",
//     //     previousInvolvement: originalData?.previousInvolvement ? "yes" : (originalData?.previousInvolvement === false ? "no" : null),
//     //     previousInvolvementExplain: originalData?.previousInvolvementExplain || "",
//     //     parentalCapacityDone: originalData?.parentalCapacityDone ? "yes" : (originalData?.parentalCapacityDone === false ? "no" : null),
//     //     parentalCapacity: originalData?.parentalCapacity || "",
//     //     cfsExplain: originalData?.cfsExplain ? "yes" : (originalData?.cfsExplain === false ? "no" : null),
//     //     turnToKinshipCare: originalData?.turnToKinshipCare ? "yes" : (originalData?.turnToKinshipCare === false ? "no" : null),

//     //     sourceIncome: originalData.sourceIncome !== null && originalData.sourceIncome !== undefined ? originalData.sourceIncome : "",
//     //     lawyerFullName:originalData?.lawyerFullName || "",
//     //     lawyerPhoneNumber:originalData?.lawyerPhoneNumber || "",
//     //     lawyerEmail: originalData?.lawyerEmail || "",

//     //     children: childrenData.map(child => ({
//     //         firstName: child.firstName || "",
//     //         middleName: child.middleName || "",
//     //         lastName: child.lastName || "",
//     //         birthDate: child.birthDate || "",
//     //         childNation: child.childNation || "",
//     //         gender: child.gender || "",
//     //         childPlaced: child.childPlaced || "",
//     //         childCfsAgency: child.childCfsAgency || "",
//     //         childCfsAgentFullName: child.childCfsAgentFullName || "",
//     //         childCfsAgentNumber: child.childCfsAgentNumber !== null && child.childCfsAgentNumber !== undefined ? child.childCfsAgentNumber : "",
//     //         childCfsAgentEmail: child.childCfsAgentEmail || "",
//     //         childStatusCfsFile: child.childStatusCfsFile !== "" ? child.childStatusCfsFile : "",
//     //         childCfsSupervisorFullName: child.childCfsSupervisorFullName || "",
//     //         childCfsSupervisorNumber: child.childCfsSupervisorNumber !== null && child.childCfsSupervisorNumber !== undefined ? child.childCfsSupervisorNumber : "",
//     //         childCfsSupervisorEmail: child.childCfsSupervisorEmail || "",
//     //         childMedicalNeeds: child?.childMedicalNeeds ? "yes" : (child?.childMedicalNeeds === false ? "no" : null),
//     //         childMedicalNeedsExplained: child?.childMedicalNeedsExplained || "",
//     //         biologicalParentFirstName:child.biologicalParentFirstName || "",
//     //         biologicalParentLastName:child.biologicalParentLastName || "",
//     //         biologicalParentFirstNation:child.biologicalParentFirstNation || "",
//     //    })) || [],
//     //     notes: notesData || [],
//     //     caseNotes: caseNotes || [],
//     //     legalNotes: legalNotes || [],

//     //     family: familyData || [],
//     //     EIA: EIAData.map(worker => ({
//     //         firstName: worker.firstName || "",
//     //         lastName: worker.lastName || "",
//     //         phoneNumber: worker.phoneNumber || "",
//     //         EIACaseNumber: worker.EIACaseNumber || "",
//     //     }))|| [],

//     //     homeMembers: homeMembersData || [],
//     // }
// });