// Helper function to convert boolean to yes/no for radio buttons
const convertBooleanToYesNo = (value) => {
    if (value === true) return "yes";
    if (value === false) return "no";
    return ""; // Return empty string instead of null for unselected radio buttons
};

export const getFormInitialValues = ({
    originalData = {},
    childrenData = [],
    notesData = [],
    caseNotes = [],
    legalNotes = [],
    familyData = [],
    EIAData = [],
    homeMembersData = [],
    } = {}) => ({
    firstName: originalData?.firstName || "",
    middleName: originalData?.middleName || "",
    lastName: originalData?.lastName || "",
    dateOfBirth: originalData?.dateOfBirth ? originalData.dateOfBirth.split("T")[0] : "",
    phoneNumber: originalData?.phoneNumber || "",
    address: originalData?.address || "",
    city: originalData?.city || "",
    province: originalData?.province || "",
    postalCode: originalData?.postalCode || "",
    email: originalData?.email || "",
    relationshipToChildren: originalData?.relationshipToChildren || "",
    otherAdultsInvolved: originalData?.otherAdultsInvolved || "",
    otherAdultsInvolvedExplained: originalData?.otherAdultsInvolvedExplained || "",
    firstNationMembership: originalData?.firstNationMembership || "",
    treatyNumber: originalData?.treatyNumber || "",
    otherFirstNation: originalData?.otherFirstNation || "",
    ninePersonalHealthNumber: originalData?.ninePersonalHealthNumber || "",
    sixPersonalHealthNumber: originalData?.sixPersonalHealthNumber || "",
    onReserve: convertBooleanToYesNo(originalData?.onReserve),
    transitionFromReserve: convertBooleanToYesNo(originalData?.transitionFromReserve),
    previousFNFAOClient: convertBooleanToYesNo(originalData?.previousFNFAOClient),
    visitsChildFrequency: originalData?.visitsChildFrequency || "",
    casePlanCopy: convertBooleanToYesNo(originalData?.casePlanCopy),
    casePlanCopyDescribe: originalData?.casePlanCopyDescribe || "",
    prenatalSupport: convertBooleanToYesNo(originalData?.prenatalSupport),
    prenatalSupportSpecified: originalData?.prenatalSupportSpecified || "",
    housingSupport: convertBooleanToYesNo(originalData?.housingSupport),
    housingSupportSpecified: originalData?.housingSupportSpecified || "",
    addictionsSupport: convertBooleanToYesNo(originalData?.addictionsSupport),
    addictionsSupportSpecified: originalData?.addictionsSupportSpecified || "",
    youthSupport: convertBooleanToYesNo(originalData?.youthSupport),
    youthSupportSpecified: originalData?.youthSupportSpecified || "",
    custodySupport: convertBooleanToYesNo(originalData?.custodySupport),
    custodySupportSpecified: originalData?.custodySupportSpecified || "",
    criminalCharges: convertBooleanToYesNo(originalData?.criminalCharges),
    criminalChargesSpecified: originalData?.criminalChargesSpecified || "",
    activeWarrant: convertBooleanToYesNo(originalData?.activeWarrant),
    activeWarrantSpecified: originalData?.activeWarrantSpecified || "",
    activeInvestigation: convertBooleanToYesNo(originalData?.activeInvestigation),
    activeInvestigationExplained: originalData?.activeInvestigationExplained || "",
    activeOrders: convertBooleanToYesNo(originalData?.activeOrders),
    activeOrdersExplained: originalData?.activeOrdersExplained || "",
    currentLawyer: convertBooleanToYesNo(originalData?.currentLawyer),
    legalAssistance: convertBooleanToYesNo(originalData?.legalAssistance),
    legalAssistanceSpecified: originalData?.legalAssistanceSpecified || "",
    martialStatus: originalData?.martialStatus || "",
    dateModified: originalData?.dateModified ? originalData.dateModified.split("T")[0] : "",
    modifiedBy: originalData?.modifiedBy || "",
    createdAt: originalData?.createdAt ? originalData.createdAt.split("T")[0] : "",


    /*  residentialSchool: convertBooleanToYesNo(originalData?.residentialSchool),
    cfsCare: convertBooleanToYesNo(originalData?.cfsCare),
    adoptedScoop: convertBooleanToYesNo(originalData?.adoptedScoop),
    experiencedSuicide: convertBooleanToYesNo(originalData?.experiencedSuicide),
    MMIWG2S: convertBooleanToYesNo(originalData?.MMIWG2S),
    familyViolence: convertBooleanToYesNo(originalData?.familyViolence), */



    /*  FASD: convertBooleanToYesNo(originalData?.FASD),
    ADHD: convertBooleanToYesNo(originalData?.ADHD),
    PTSD: convertBooleanToYesNo(originalData?.PTSD),
    depression: convertBooleanToYesNo(originalData?.depression),
    cancerAutoimmuneCondition: convertBooleanToYesNo(originalData?.cancerAutoimmuneCondition),
    otherMentalCondition: convertBooleanToYesNo(originalData?.otherMentalCondition), */

    // Fixes checkbox UI, no need to convert to yes / no string as their already bools unlike radio.
    residentialSchool: !!originalData?.residentialSchool,
    cfsCare: !!originalData?.cfsCare,
    adoptedScoop: !!originalData?.adoptedScoop,
    experiencedSuicide: !!originalData?.experiencedSuicide,
    MMIWG2S: !!originalData?.MMIWG2S,
    familyViolence: !!originalData?.familyViolence,

    FASD: !!originalData?.FASD,
    ADHD: !!originalData?.ADHD,
    PTSD: !!originalData?.PTSD,
    depression: !!originalData?.depression,
    cancerAutoimmuneCondition: !!originalData?.cancerAutoimmuneCondition,
    otherMentalCondition: !!originalData?.otherMentalCondition,


    
    otherMentalConditionExplained: originalData?.otherMentalConditionExplained || "",
    diagnosedFollowingExplain: originalData?.diagnosedFollowingExplain || "",
    negativeCopingSkills: convertBooleanToYesNo(originalData?.negativeCopingSkills),
    negativeCopingSkillsExplain: originalData?.negativeCopingSkillsExplain || "",
    drugsImpact: originalData?.drugsImpact || "",
    lastTimeUsed: originalData?.lastTimeUsed || "",
    educationalGoals: convertBooleanToYesNo(originalData?.educationalGoals),
    educationalGoalsExplained: originalData?.educationalGoalsExplained || "",
    accessElder: convertBooleanToYesNo(originalData?.accessElder),
    accessElderExplained: originalData?.accessElderExplained || "",
    childrenInCareDuration: originalData?.childrenInCareDuration || "",
    cfsChildrenApprehesionReason: originalData?.cfsChildrenApprehesionReason || "",
    kinship: convertBooleanToYesNo(originalData?.kinship),
    kinshipExplained: originalData?.kinshipExplained || "",
    anyConcerns: originalData?.anyConcerns || "",
    prentativeSupport: convertBooleanToYesNo(originalData?.prentativeSupport),
    prentativeSupportExplained: originalData?.prentativeSupportExplained || "",
    privateAgreement: convertBooleanToYesNo(originalData?.privateAgreement),
    privateAgreementExplained: originalData?.privateAgreementExplained || "",
    previousInvolvement: convertBooleanToYesNo(originalData?.previousInvolvement),
    previousInvolvementExplain: originalData?.previousInvolvementExplain || "",
    parentalCapacityDone: convertBooleanToYesNo(originalData?.parentalCapacityDone),
    parentalCapacity: originalData?.parentalCapacity || "",
    cfsExplain: convertBooleanToYesNo(originalData?.cfsExplain),
    turnToKinshipCare: convertBooleanToYesNo(originalData?.turnToKinshipCare),
    sourceIncome: originalData?.sourceIncome !== null && originalData?.sourceIncome !== undefined ? originalData.sourceIncome : "",
    lawyerFullName: originalData?.lawyerFullName || "",
    lawyerPhoneNumber: originalData?.lawyerPhoneNumber || "",
    lawyerEmail: originalData?.lawyerEmail || "",
    children: childrenData.map(child => ({
        firstName: child.firstName || "",
        middleName: child.middleName || "",
        lastName: child.lastName || "",
        birthDate: child.birthDate || "",
        childNation: child.childNation || "",
        gender: child.gender || "",
        childPlaced: child.childPlaced || "",
        childCfsAgency: child.childCfsAgency || "",
        childCfsAgentFullName: child.childCfsAgentFullName || "",
        childCfsAgentNumber: child.childCfsAgentNumber !== null && child.childCfsAgentNumber !== undefined ? child.childCfsAgentNumber : "",
        childCfsAgentEmail: child.childCfsAgentEmail || "",
        childStatusCfsFile: child.childStatusCfsFile || "",
        childCfsSupervisorFullName: child.childCfsSupervisorFullName || "",
        childCfsSupervisorNumber: child.childCfsSupervisorNumber !== null && child.childCfsSupervisorNumber !== undefined ? child.childCfsSupervisorNumber : "",
        childCfsSupervisorEmail: child.childCfsSupervisorEmail || "",
        childMedicalNeeds: convertBooleanToYesNo(child?.childMedicalNeeds),
        childMedicalNeedsExplained: child?.childMedicalNeedsExplained || "",
        biologicalParentFirstName: child.biologicalParentFirstName || "",
        biologicalParentLastName: child.biologicalParentLastName || "",
        biologicalParentFirstNation: child.biologicalParentFirstNation || "",
    })) || [],
    notes: notesData || [],
    caseNotes: caseNotes || [],
    legalNotes: legalNotes || [],
    family: familyData || [],
    EIA: EIAData.map(worker => ({
        firstName: worker.firstName || "",
        lastName: worker.lastName || "",
        phoneNumber: worker.phoneNumber || "",
        EIACaseNumber: worker.EIACaseNumber || "",
    })) || [],
    homeMembers: homeMembersData.map(member => ({
        firstName: member.firstName || "",
        lastName: member.lastName || "",
        relationship: member.relationship || "",
        phoneNumber: member.phoneNumber || "",
        email: member.email || "",
        livingTogether: member.livingTogether
    })) || [],
    });