import { jsPDF } from 'jspdf';

/**
 * This is a helper function to generate PDF documents from an input, and
 * format it to fit on multiple pages. This code was generated by GitHub
 * Co-Pilot GPT-5 mini, and edited by Dominik Kananowicz.
 * 
 * Does not return anything, but instead just downloads itself.
 * @param {*} text Input text for the PDF
 * @param {*} filename filename for the PDF, must include .pdf at the end
 */
export function saveLongPdf(text, filename) {
    const doc = new jsPDF('p', 'mm', 'a4'); // units mm for easier math
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 15;
    const fontSize = 11;
    doc.setFontSize(fontSize);

    const usableW = pageW - margin * 2;
    // split into lines that fit width
    const lines = doc.splitTextToSize(text, usableW);

    // approximate line height in mm (fontSize is in pt -> roughly fontSize * 0.3528 mm)
    const lineHeight = (fontSize * 0.3528) * 1.15;
    const linesPerPage = Math.floor((pageH - margin * 2) / lineHeight);

    let cursor = 0;
    while (cursor < lines.length) {
        const chunk = lines.slice(cursor, cursor + linesPerPage);
        const startY = margin + (fontSize * 0.3528); // start a bit below top margin
        doc.text(chunk, margin, startY);
        cursor += chunk.length;
        if (cursor < lines.length) doc.addPage();
    }

    const blob = doc.output("blob");
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}